export default {
  DEFAULT: 'xgplayer',
  DEFAULT_SKIN: 'xgplayer-skin-default',
  ENTER: 'xgplayer-is-enter',
  PAUSED: 'xgplayer-pause',
  PLAYING: 'xgplayer-playing',
  ENDED: 'xgplayer-ended',
  CANPLAY: 'xgplayer-canplay',
  LOADING: 'xgplayer-isloading',
  ERROR: 'xgplayer-error',
  REPLAY: 'xgplayer-replay',
  NO_START: 'xgplayer-nostart',
  ACTIVE: 'xgplayer-inactive',
  FULLSCREEN: 'xgplayer-is-fullscreen',
  CSS_FULLSCREEN: 'xgplayer-is-cssfullscreen',
  NO_CONTROLS: 'no-controls',
  NOT_ALLOW_AUTOPLAY: 'not-allow-autoplay',
  PC: 'xgplayer-pc',
  MOBILE: 'xgplayer-mobile',
  MINI: 'xgplayer-mini'
};