// Common Events
export const AD_START = 'ad_start'
export const AD_PLAY = 'ad_play'
export const AD_PAUSE = 'ad_pause'
export const AD_TIME_UPDATE = 'ad_time_update'
export const AD_COMPLETE = 'ad_complete'
export const AD_ALL_COMPLETED = 'ad_all_completed'

// IMA Specific Events
export const IMA_SDK_LOAD_SUCCESS = 'ima_sdk_load_success'
export const IMA_SDK_LOAD_ERROR = 'ima_sdk_load_error'
export const IMA_AD_LOADER_READY = 'ima_ad_loader_ready'
export const IMA_AD_MANAGER_READY = 'ima_ad_manager_ready'
export const IMA_AD_ENDED = 'ima_ad_ended'
export const IMA_AD_SKIPPED = 'ima_ad_skipped'
export const IMA_AD_COMPLETE = 'ima_ad_complete'
export const IMA_ALL_ADS_COMPLETED = 'ima_all_ads_completed'
export const IMA_AD_ERROR = 'ima_ad_error'
export const IMA_AD_SEEKING = 'ima_ad_seeking'
export const IMA_AD_SEEKED = 'ima_ad_seeked'
export const IMA_AD_LOADED = 'ima_ad_loaded'
export const IMA_AD_BREAK_READY = 'ima_ad_break_ready'
export const IMA_CONTENT_PAUSE_REQUESTED = 'ima_content_pause_requested'
export const IMA_CONTENT_RESUME_REQUESTED = 'ima_content_resume_requested'
export const IMA_READY_TO_PLAY = 'ima_ready_to_play'
