const fs = require('node:fs')
const path = require('node:path')

const { getRepoRoot } = require('./source-build')

const VENDOR_FILES = ['hls.js', 'hls.light.js']
const GENERATED_HEADER =
  '/* Auto-generated by hlsjs:patch:sync-vendor. Do not edit directly. */'

function ensureDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true })
}

function readUtf8(filePath) {
  return fs.readFileSync(filePath, 'utf8')
}

function assertIncludes(filePath, needle) {
  const content = readUtf8(filePath)
  if (!content.includes(needle)) {
    throw new Error(
      `[hlsjs-sei-patch] vendor sync failed: ${path.relative(process.cwd(), filePath)} missing "${needle}"`
    )
  }
}

function writeVendorModule({ from, to }) {
  const content = readUtf8(from)
  fs.writeFileSync(to, `${GENERATED_HEADER}\n${content}\nexport default Hls\n`)
}

function writeVendorReadme(vendorDir) {
  fs.writeFileSync(
    path.join(vendorDir, 'README.md'),
    `# Auto-generated hls.js vendor files

Files in this directory are generated by:

\`\`\`bash
yarn workspace xgplayer-hls.js hlsjs:patch:sync-vendor
\`\`\`

Do not edit them directly. Update the hls.js source patch, run \`hlsjs:patch:regen\` or \`hlsjs:patch:apply\`, then commit the regenerated vendor files.
`
  )
}

function copyPatchedHlsVendor({ repoRoot = getRepoRoot() } = {}) {
  const hlsDist = path.join(repoRoot, 'node_modules', 'hls.js', 'dist')
  const vendorDir = path.join(repoRoot, 'packages', 'xgplayer-hls.js', 'src', 'vendor')

  ensureDir(vendorDir)
  writeVendorReadme(vendorDir)

  for (const fileName of VENDOR_FILES) {
    const from = path.join(hlsDist, fileName)
    const to = path.join(vendorDir, fileName)

    if (!fs.existsSync(from)) {
      throw new Error(`[hlsjs-sei-patch] patched hls.js dist missing: ${from}`)
    }

    writeVendorModule({ from, to })
    assertIncludes(to, 'customSeiMessage: true')
  }

  process.stdout.write(
    `[hlsjs-sei-patch] Synced patched hls.js vendor files: ${VENDOR_FILES.join(', ')}\n`
  )
}

if (require.main === module) {
  copyPatchedHlsVendor()
}

module.exports = {
  VENDOR_FILES,
  copyPatchedHlsVendor
}
